### ISSUE TITLE
Careful now

### ISSUE THREAD

**Issue by spikything** [PeteDevoy/cutiebomb-server#8]
As the original developer of Dinky Bomb, I can tell you how nasty the rights holder's lawyers can be. I'd be very careful on your current path. I wanted to bring back Dinky Bomb a few times, only to be slapped down :/

**Comment by PeteDevoy** [comment]
@spikything thanks for the heads-up and big respect to you for Dinky Bomb, one of the greatest games of the flash era -- second only, perhaps, to "Shoot Your Friends"!

I was actually going to reach out to you about the above but you beat me to it :)  Do you mind if I ping you message via your website?  It may be helpful to know who told you what...

**Comment by spikything** [comment]
Haha, thanks. Sure you can find me through my site, but I don't actually know the exact status of DB now :/
